process.env.KINDRED_TEST_SECURITY_HEADERS='1';
const {server,token}=require('./fixtures/desktop.cjs'),{chromium,webkit}=require(process.env.KINDRED_PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await(process.env.WEBKIT?webkit:chromium).launch();try{
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),origin='http://127.0.0.1:'+server.address().port,out='/opt/kindred/testing/shards',engine=(process.env.WEBKIT?'webkit':'chromium')+(process.env.LIGHT?'-light':''),errors=[];fs.mkdirSync(out,{recursive:true});page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(t=>{if(window===top)sessionStorage.setItem('kindred-token',t)},token);
 if(process.env.LIGHT)await page.route(origin+'/api/settings',r=>r.fulfill({json:{name:'You',theme:'light',reduced_motion:false}}));await page.route(origin+'/api/runs',r=>r.fulfill({json:[]}));
 const html=`<style>body{padding:22px!important}h2{font-size:19px;margin:0 0 5px}p{opacity:.65;font-size:13px;margin:0 0 18px}.palettes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}button{color:inherit;background:transparent;border:1px solid #8885;border-radius:10px;overflow:hidden;padding:0;text-align:left}button[aria-pressed=true]{outline:2px solid #66bea6;outline-offset:2px}.swatches{display:flex;height:60px}.swatches i{flex:1}label{display:block;padding:10px;font-size:12px}footer{font-size:12px;opacity:.7;margin-top:15px}</style><h2>Three directions for the launch</h2><p>Choose a palette to compare how it feels.</p><div class="palettes"><button aria-pressed="true" onclick="pick(this,'Coastal')"><span class="swatches"><i style="background:#124e5a"></i><i style="background:#72b6a1"></i><i style="background:#ece4d2"></i></span><label>Coastal</label></button><button aria-pressed="false" onclick="pick(this,'Orchard')"><span class="swatches"><i style="background:#553447"></i><i style="background:#c58b8b"></i><i style="background:#f3dec1"></i></span><label>Orchard</label></button><button aria-pressed="false" onclick="pick(this,'Electric')"><span class="swatches"><i style="background:#373080"></i><i style="background:#a096eb"></i><i style="background:#d5ed82"></i></span><label>Electric</label></button></div><footer id="selection">Coastal selected · calm, clear, grounded</footer><script>function pick(button,name){document.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));selection.textContent=name+' selected';}</script>`;
 const jsx=`import React,{useState} from 'react';export default function App(){const [ready,setReady]=useState(false);const rows=[['Launch page','Ready','Piper'],['Brand assets','Ready','Rowan'],['Release notes','Draft','Piper']];return <main style={{padding:6}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><h2 style={{fontSize:19,margin:0}}>A quick review queue</h2><button onClick={()=>setReady(!ready)} style={{color:'inherit',border:'1px solid #8885',borderRadius:20,background:ready?'#459d8530':'transparent',padding:'6px 12px',fontSize:12}}>{ready?'Show all':'Ready only'}</button></header><table style={{width:'100%',borderCollapse:'collapse',fontSize:13,textAlign:'left'}}><thead><tr>{['Deliverable','Status','Owner'].map(c=><th key={c} style={{padding:'9px 0',opacity:.6,fontWeight:400}}>{c}</th>)}</tr></thead><tbody>{rows.filter(r=>!ready||r[1]==='Ready').map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i} style={{padding:'12px 0',borderTop:'1px solid #8883',color:i===1&&c==='Ready'?'#59ba97':'inherit'}}>{c}</td>)}</tr>)}</tbody></table></main>}`;
 const fence=(lang,s)=>'```'+lang+'\n'+s+'\n```';let messages=[{seq:1,sender:'user',kind:'message',text:'Show me three palettes, and a small interactive review table.',created:1},{seq:2,sender:'piper',kind:'result',text:'Coastal would be my pick. Click the others to compare.\n\n'+fence('shard-html',html),created:2},{seq:3,sender:'piper',kind:'result',text:fence('shard-jsx',jsx),created:3}];await page.route(origin+'/api/chats/dm-piper*',r=>r.fulfill({json:{chat:{id:'dm-piper',name:'Piper',members:['piper']},messages,page:{has_before:false,has_after:false}}}));
 await page.goto(origin);const palette=page.frameLocator('.shard-frame').nth(0),table=page.frameLocator('.shard-frame').nth(1);await palette.getByText('Three directions for the launch',{exact:true}).waitFor();await table.getByText('Release notes',{exact:true}).waitFor();assert.equal(await page.locator('#content pre,#content .artifact-toolbar').count(),0);await palette.getByRole('button',{name:'Orchard'}).click();await palette.getByText('Orchard selected',{exact:true}).waitFor();await table.getByRole('button',{name:'Ready only'}).click();assert.equal(await table.getByText('Release notes',{exact:true}).count(),0);await table.getByRole('button',{name:'Show all'}).click();await page.waitForTimeout(300);await page.screenshot({path:out+'/inline-'+engine+'.png'});
 const before=page.frames().slice(1);messages.push({seq:4,sender:'user',kind:'message',text:'Keep Orchard for now.',created:4});await page.getByText('Keep Orchard for now.',{exact:true}).waitFor();await palette.getByText('Orchard selected',{exact:true}).waitFor();assert.deepEqual(page.frames().slice(1),before);
 messages[1].text+='\n\nOrchard also works well for the event materials.';await page.getByText('Orchard also works well for the event materials.',{exact:true}).waitFor();await palette.getByText('Orchard selected',{exact:true}).waitFor();assert.deepEqual(page.frames().slice(1),before);
 messages.push({seq:5,sender:'piper',kind:'result',text:'```shard-html\n<h1>Not complete',created:5});await page.locator('#content .shard-loading').getByText('Building view…',{exact:true}).waitFor();assert.equal(await page.locator('.shard-frame').count(),2);
 messages[4].text=fence('shard-html','<h1>Now complete</h1>');await page.frameLocator('.shard-frame').nth(2).getByText('Now complete',{exact:true}).waitFor();messages.push({seq:6,sender:'piper',kind:'result',text:fence('html-source','<p>Keep this as source</p>'),created:6});await page.locator('#content pre').getByText('<p>Keep this as source</p>',{exact:true}).waitFor();assert.equal(await page.locator('.shard-frame').count(),3);assert.deepEqual(errors,[]);console.log('PASS HTML/React shards render directly, theme, controls, stable state, streaming completion, source-only fences');
}finally{await browser.close();server.closeAllConnections();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
