"""Generate frontend metadata from the shared, reviewed connector registry."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
rows=json.loads((root/'ui/connector-catalog.json').read_text(encoding='utf8'))
assert len({r['id'] for r in rows})==len(rows)
public=[{k:r[k] for k in ['id','name','family','aliases','description']} for r in rows]
(root/'ui/connector-catalog.js').write_text('// Generated by scripts/generate-connector-catalog.py.\nexport const connectorCatalog = '+json.dumps(public,separators=(',',':'))+';\n',encoding='utf8',newline='\n')
