// Native Kindred documents/sheets. Custom applications keep their source editor.
import {DOMPurify,marked} from './vendor.js';
const DOC='<!--kindred-document-v1-->';
export function visualArtifactKind(v){
 if((v.kind==='document'||(!v.kind&&v.language==='markdown'))&&(v.language==='markdown'||v.source?.startsWith(DOC)))return 'document';
 if(v.kind==='sheet'&&Array.isArray(v.state?.rows)&&(v.source?.includes('kindred-sheet-v1')||v.source?.includes('let rows=[];kindredArtifact.ready')))return 'sheet';
 return null;
}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(label,fn,text=label)=>{const b=el('button','artifact-format-button',text);b.type='button';b.title=label;b.setAttribute('aria-label',label);b.onclick=fn;return b;};
const select=(label,options,fn)=>{const s=el('select');s.setAttribute('aria-label',label);s.title=label;for(const [value,text] of options)s.append(new Option(text,value));s.onchange=()=>fn(s.value);return s;};
const fonts=[['Inter','Sans serif'],['Georgia','Serif'],['Arial','Arial'],['Courier New','Monospace']];
const sizes=[10,12,14,16,18,20,24,28,32,40,48].map(n=>[String(n),String(n)]);
const clean=html=>DOMPurify.sanitize(html,{USE_PROFILES:{html:true},FORBID_TAGS:['style','form','input','button','textarea','select','iframe','video','audio'],FORBID_ATTR:['id','class'],ALLOW_DATA_ATTR:false});
const paperStyle='body{margin:0;padding:24px;font:16px/1.6 Inter,system-ui,sans-serif;overflow-wrap:anywhere}main{max-width:820px;margin:auto}p{margin:.5em 0}table{border-collapse:collapse;width:100%}td,th{border:1px solid #8886;padding:8px;vertical-align:top}img{max-width:100%;height:auto}blockquote{border-left:3px solid #8886;padding-left:16px;margin-left:0}pre{white-space:pre-wrap}';
export async function createArtifactEditor(value,{onDirty=()=>{}}={}){
 if(visualArtifactKind(value)==='sheet')return sheetEditor(value,onDirty);
 const {Editor,StarterKit,TextStyleKit,TextAlign,TableKit,Image}=await import('./editor-vendor.js');
 const root=el('div','artifact-visual-editor'),toolbar=el('div','artifact-format-toolbar'),canvas=el('div','artifact-document-canvas'),surface=el('div','artifact-document-surface');
 toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Document formatting');canvas.append(surface);root.append(toolbar,canvas);
 let content=value.language==='markdown'?marked.parse(value.source||''):new DOMParser().parseFromString(value.source,'text/html').querySelector('main')?.innerHTML||'';
 const editor=new Editor({element:surface,extensions:[StarterKit.configure({link:{openOnClick:false}}),TextStyleKit,TextAlign.configure({types:['heading','paragraph']}),TableKit,Image.configure({allowBase64:false})],content:clean(content),editorProps:{attributes:{'aria-label':'Document content',role:'textbox','aria-multiline':'true',spellcheck:'true'},transformPastedHTML:clean},onUpdate:()=>onDirty()});
 const active=[];
 const command=(label,text,run,mark)=>{const b=button(label,()=>run(editor.chain().focus()).run(),text);b.onpointerdown=e=>e.preventDefault();if(mark)active.push([b,mark]);toolbar.append(b);return b;};
 const block=select('Paragraph style',[['p','Normal text'],['1','Heading 1'],['2','Heading 2'],['3','Heading 3']],v=>{const c=editor.chain().focus();(v==='p'?c.setParagraph():c.setHeading({level:Number(v)})).run();});
 const font=select('Font family',fonts,v=>editor.chain().focus().setFontFamily(v).run());
 const size=select('Font size',sizes,v=>editor.chain().focus().setFontSize(v+'px').run());size.value='16';toolbar.append(block,font,size);
 command('Bold','B',c=>c.toggleBold(),'bold').style.fontWeight='700';command('Italic','I',c=>c.toggleItalic(),'italic').style.fontStyle='italic';command('Underline','U',c=>c.toggleUnderline(),'underline').style.textDecoration='underline';
 command('Bulleted list','• List',c=>c.toggleBulletList(),'bulletList');command('Numbered list','1. List',c=>c.toggleOrderedList(),'orderedList');
 toolbar.append(select('Text alignment',[['left','Align left'],['center','Center'],['right','Align right']],v=>editor.chain().focus().setTextAlign(v).run()));
 command('Undo','↶',c=>c.undo());command('Redo','↷',c=>c.redo());
 const more=el('details','artifact-format-more');more.append(el('summary','','More'));const extras=el('div','artifact-format-extras');
 const linkField=el('input');linkField.type='url';linkField.placeholder='https://';linkField.setAttribute('aria-label','Link address');
 extras.append(linkField,button('Apply link',()=>{const href=linkField.value.trim();if(!/^(https?:\/\/|mailto:)/i.test(href)){linkField.setCustomValidity('Use an https, http or mailto address.');linkField.reportValidity();return;}linkField.setCustomValidity('');editor.chain().focus().extendMarkRange('link').setLink({href}).run();more.open=false;}),button('Remove link',()=>editor.chain().focus().unsetLink().run()),button('Insert table',()=>{editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run();more.open=false;}),button('Add table row',()=>editor.chain().focus().addRowAfter().run()),button('Add table column',()=>editor.chain().focus().addColumnAfter().run()),button('Delete table',()=>editor.chain().focus().deleteTable().run()),button('Clear formatting',()=>editor.chain().focus().unsetAllMarks().clearNodes().run()));
 const color=el('input');color.type='color';color.setAttribute('aria-label','Text color');color.oninput=()=>editor.chain().focus().setColor(color.value).run();extras.append(color);more.append(extras);toolbar.append(more);
 const update=()=>{for(const [b,mark] of active)b.setAttribute('aria-pressed',String(editor.isActive(mark)));block.value=String(editor.getAttributes('heading').level||'p');font.value=editor.getAttributes('textStyle').fontFamily||'Inter';size.value=String(parseFloat(editor.getAttributes('textStyle').fontSize)||16);};editor.on('selectionUpdate',update);editor.on('transaction',update);update();
 return {root,destroy:()=>editor.destroy(),snapshot:()=>{const html=editor.getHTML(),source=DOC+'<style>'+paperStyle+'</style><main>'+html+'</main>';return {language:'html',source,state:{...value.state,kindredDocument:{version:1,html,document:editor.getJSON()}}};}};
}
const letters=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
function sheetEditor(value,onDirty){
 let rows=structuredClone(value.state.rows).map(r=>Array.isArray(r)?r.map(v=>String(v??'')):[]),styles=structuredClone(value.state.cellStyles||{}),selected=[0,0],history=[],future=[];
 if(!rows.length)rows=[['']];let cols=Math.max(1,...rows.map(r=>r.length));for(const r of rows)while(r.length<cols)r.push('');
 if(rows.length*cols>10000)throw Error('This sheet is too large for the basic editor. Open its existing preview instead.');
 const root=el('div','artifact-visual-editor artifact-sheet-editor'),bar=el('div','artifact-format-toolbar'),formula=el('div','artifact-formula-bar'),address=el('span','','A1'),input=el('input'),viewport=el('div','artifact-sheet-viewport'),table=el('table','artifact-sheet-grid');
 bar.setAttribute('role','toolbar');bar.setAttribute('aria-label','Sheet formatting');input.setAttribute('aria-label','Cell value');formula.append(address,input);viewport.append(table);root.append(bar,formula,viewport);
 const snapshot=()=>JSON.stringify({rows,styles});
 function change(fn,redraw=true){const before=snapshot();fn();if(snapshot()!==before){history.push(before);if(history.length>100)history.shift();future=[];onDirty();}if(redraw)paint();}
 function restore(from,to){if(!from.length)return;to.push(snapshot());const s=JSON.parse(from.pop());rows=s.rows;styles=s.styles;cols=rows[0].length;selected=[Math.min(selected[0],rows.length-1),Math.min(selected[1],cols-1)];onDirty();paint();}
 const key=()=>selected.join(':');const apply=patch=>change(()=>styles[key()]={...styles[key()],...patch});
 bar.append(select('Font family',fonts,fontFamily=>apply({fontFamily})),select('Font size',sizes,fontSize=>apply({fontSize:fontSize+'px'})),button('Bold',()=>apply({fontWeight:styles[key()]?.fontWeight==='700'?'400':'700'}),'B'),button('Italic',()=>apply({fontStyle:styles[key()]?.fontStyle==='italic'?'normal':'italic'}),'I'),select('Text alignment',[['left','Align left'],['center','Center'],['right','Align right']],textAlign=>apply({textAlign})),button('Undo',()=>restore(history,future),'↶'),button('Redo',()=>restore(future,history),'↷'));
 const color=el('input');color.type='color';color.setAttribute('aria-label','Cell text color');color.onchange=()=>apply({color:color.value});bar.append(color);
 const addRow=button('Add row',()=>{if((rows.length+1)*cols>10000)return;change(()=>rows.push(Array(cols).fill('')));});
 const addCol=button('Add column',()=>{if(rows.length*(cols+1)>10000)return;change(()=>{rows.forEach(r=>r.push(''));cols++;});});bar.append(addRow,addCol,button('Clear cell',()=>change(()=>rows[selected[0]][selected[1]]='')));
 function choose(i,j){selected=[i,j];address.textContent=letters(j)+(i+1);input.value=rows[i][j];const st=styles[i+':'+j]||{};bar.querySelector('[aria-label="Font family"]').value=st.fontFamily||'Inter';bar.querySelector('[aria-label="Font size"]').value=String(parseFloat(st.fontSize)||16);bar.querySelector('[aria-label="Text alignment"]').value=st.textAlign||'left';bar.querySelector('[aria-label="Bold"]').setAttribute('aria-pressed',String(st.fontWeight==='700'));bar.querySelector('[aria-label="Italic"]').setAttribute('aria-pressed',String(st.fontStyle==='italic'));table.querySelector('.selected')?.classList.remove('selected');table.querySelector(`[data-row="${i}"][data-col="${j}"]`)?.classList.add('selected');}
 function paste(text,i,j){const data=text.replace(/\r\n?/g,'\n').replace(/\n$/,'').split('\n').map(r=>r.split('\t'));const nc=Math.max(cols,j+Math.max(...data.map(r=>r.length))),nr=Math.max(rows.length,i+data.length);if(nc*nr>10000)return;change(()=>{while(rows.length<nr)rows.push(Array(cols).fill(''));cols=nc;rows.forEach(r=>{while(r.length<cols)r.push('');});data.forEach((r,a)=>r.forEach((v,b)=>rows[i+a][j+b]=v));});}
 input.oninput=()=>onDirty();
 input.onchange=()=>{change(()=>rows[selected[0]][selected[1]]=input.value,false);const cell=table.querySelector(`[data-row="${selected[0]}"][data-col="${selected[1]}"] input`);if(cell)cell.value=input.value;};
 input.onpaste=e=>{const text=e.clipboardData?.getData('text/plain');if(text?.includes('\t')||text?.includes('\n')){e.preventDefault();paste(text,...selected);}};
 function paint(){table.replaceChildren();const head=el('tr');head.append(el('th'));for(let j=0;j<cols;j++)head.append(el('th','',letters(j)));table.append(head);
 rows.forEach((row,i)=>{const tr=el('tr');tr.append(el('th','',String(i+1)));row.forEach((v,j)=>{const td=el('td');td.dataset.row=i;td.dataset.col=j;const cell=el('input');cell.value=v;cell.setAttribute('aria-label',letters(j)+(i+1));cell.onfocus=()=>choose(i,j);cell.oninput=()=>onDirty();cell.onchange=()=>{change(()=>rows[i][j]=cell.value,false);if(selected[0]===i&&selected[1]===j)input.value=cell.value;};cell.onpaste=e=>{const text=e.clipboardData?.getData('text/plain');if(text?.includes('\t')||text?.includes('\n')){e.preventDefault();paste(text,i,j);}};cell.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();cell.blur();const next=table.querySelector(`[data-row="${Math.min(rows.length-1,i+1)}"][data-col="${j}"] input`);next?.focus();}};const style=styles[i+':'+j]||{};for(const prop of ['fontFamily','fontSize','fontWeight','fontStyle','textAlign','color'])if(typeof style[prop]==='string')cell.style[prop]=style[prop];td.append(cell);tr.append(td);});table.append(tr);});choose(...selected);}
 paint();return {root,destroy(){},snapshot:()=>{const saved=rows.map(r=>[...r]);for(const td of table.querySelectorAll('td'))saved[Number(td.dataset.row)][Number(td.dataset.col)]=td.firstChild.value;if(document.activeElement===input)saved[selected[0]][selected[1]]=input.value;return {state:{...value.state,rows:saved,cellStyles:styles},source:sheetSource(),language:'html'};}};
}
export function sheetSource(){return `<!--kindred-sheet-v1--><style>${paperStyle}th{opacity:.65;font-weight:500}td{min-width:100px}</style><main><table id="sheet"></table></main><script>kindredArtifact.ready.then(s=>{const t=document.getElementById('sheet');for(let i=0;i<(s.rows||[]).length;i++){const tr=document.createElement('tr');for(let j=0;j<s.rows[i].length;j++){const td=document.createElement('td');td.textContent=String(s.rows[i][j]??'');const st=s.cellStyles?.[i+':'+j]||{};for(const p of ['fontFamily','fontSize','fontWeight','fontStyle','textAlign','color'])if(typeof st[p]==='string')td.style[p]=st[p];tr.append(td);}t.append(tr);}});<\/script>`;}
