const el=(tag,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
const button=(text,action)=>{const b=el('button','outline-button',text);b.type='button';b.onclick=action;return b;};
export function isLocalStandalone(){return !!window.__KINDRED_PROFILE_HOST&&location.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(location.hostname)&&location.port==='9444';}
export function mountPhoneAccess(root,{nativeInvoke,onPair,workingBots=()=>0,dialog}){
 const form=el('form','standalone-access'),group=el('fieldset'),legend=el('legend','','Who can reach this Kindred');group.append(legend);
 const choices={};for(const [value,name,help] of [['local','Only this computer','Kindred is only reachable on this computer.'],['tailnet','My devices with Tailscale (recommended)','Your phone opens this same Kindred — the same account, bots and chats — from anywhere while Tailscale is on. It stays private to your Tailscale network.'],['lan','Advanced: local network','Devices on the same Wi-Fi can reach Kindred without encryption. The iPhone app needs HTTPS.']]){
  const label=el('label','access-choice'),radio=el('input');radio.type='radio';radio.name='standalone-access';radio.value=value;label.append(radio,el('strong','',name),el('span','muted',help));choices[value]=radio;group.append(label);
 }
 const setup=el('div','tailnet-setup'),steps=el('ol');for(const text of ['Install Tailscale on this computer and your phone, then sign in to the same Tailscale network.','Enable MagicDNS and HTTPS certificates in your Tailscale admin settings.','Turn on phone access below. Keep this computer awake.'])steps.append(el('li','',text));
 const guide=el('a','','Tailscale setup instructions');guide.href='https://tailscale.com/docs/features/tailscale-serve';guide.target='_blank';guide.rel='noopener noreferrer';setup.append(steps,guide);
 const advanced=el('details'),summary=el('summary','','Additional connection addresses');advanced.append(summary,el('p','muted','localhost and 127.0.0.1 both mean this computer. All interfaces allows connections through every network on this computer.'),el('p','muted','Use complete HTTP addresses for local networks or HTTPS addresses for trusted private sharing. The phone app accepts HTTPS only.'));
 const addresses=el('textarea');addresses.rows=3;addresses.setAttribute('aria-label','Additional connection addresses');advanced.append(addresses);
 const phone=el('div','phone-address'),phoneLabel=el('span'),address=el('code'),copy=button('Copy address',async()=>{try{await navigator.clipboard.writeText(address.textContent);status.textContent='Phone address copied.';}catch{error.textContent='Could not copy the address. Select it and copy it manually.';}});phone.append(phoneLabel,address,copy);
 const status=el('p','access-status','Checking phone access…');status.setAttribute('role','status');status.tabIndex=-1;
 const error=el('p','profile-form-error');error.setAttribute('role','alert');
 const actions=el('div','row-actions'),check=button('Check again',()=>update()),save=button('Save',()=>update({access:mode(),addresses:values()})),enable=button('Turn on phone access',()=>update({access:'tailnet',addresses:values(),enableTailnet:true})),pair=button('Connect mobile app',onPair),restart=button('Restart Kindred',async()=>{
  const count=workingBots();if(!confirm(`Restarting stops active bot work and computer sessions for a short time.${count?' '+count+' bot'+(count===1?' is':'s are')+' working.':''} Restart now?`))return;await update({restart:true});
 });
 const disable=button('Turn off phone access',()=>update({disableTailnet:true}));actions.append(check,save,enable,disable,restart,pair);const impact=el('p','muted access-impact','Saving does not restart Kindred. Restart when your bots have finished their work.');form.append(group,setup,advanced,phone,status,error,impact,actions);root.append(form);form.onsubmit=e=>e.preventDefault();
 let current=null,busy=false,closed=false;const mode=()=>Object.keys(choices).find(k=>choices[k].checked)||'local',values=()=>addresses.value.split('\n').map(v=>v.trim()).filter(Boolean);
 const dirty=()=>current&&(mode()!==current.access||JSON.stringify(values())!==JSON.stringify(current.addresses||[]));
 function draw(){const tailnet=mode()==='tailnet';impact.hidden=!current?.pending;setup.hidden=!tailnet;advanced.hidden=mode()==='local';phone.hidden=!tailnet||!current?.tailnet?.address;address.textContent=current?.tailnet?.address||'';phoneLabel.textContent=current?.ready_to_pair?'Phone address: ':'Will be: ';copy.hidden=!current?.ready_to_pair;save.hidden=tailnet;save.disabled=busy||!dirty();enable.hidden=!tailnet||!!current?.ready_to_pair||!!current?.pending;enable.disabled=busy||!current||!['shared','not_set_up'].includes(current.tailnet?.state);restart.hidden=!current?.pending;restart.disabled=busy||!current||dirty();disable.hidden=current?.tailnet?.state!=='shared';disable.disabled=busy;pair.hidden=!current?.ready_to_pair;pair.disabled=busy;check.disabled=busy;for(const n of [...Object.values(choices),addresses])n.disabled=busy;}
 async function update(args={}){if(busy||closed)return;busy=true;error.textContent='';status.textContent=args.enableTailnet?'Setting up private phone access…':args.restart?'Local server restarting · reconnecting…':'Checking phone access…';draw();
  try{const value=await nativeInvoke('standalone_network',args);if(closed)return;const initial=!current;current=value;if(initial||Object.keys(args).length){choices[value.access||'local'].checked=true;addresses.value=(value.addresses||[]).join('\n');}
   status.textContent=value.tailnet?.state==='problem'?'Problem · '+value.tailnet.message:value.pending?'Needs restart · Saved — restart Kindred to apply.':value.ready_to_pair?'Ready to pair · Opens this same workspace on your phone':value.tailnet?.state==='shared'?'Phone sharing is still enabled in Tailscale.':mode()==='tailnet'?(value.tailnet?.message||'Not set up'):value.access==='lan'?'Local network access is active.':'Off · Kindred listens on this computer only.';
  }catch(e){if(!closed){status.textContent='Problem';error.textContent=e.message||String(e);}}finally{busy=false;if(!closed){draw();if(Object.keys(args).length)status.focus();}}
 }
 for(const n of [...Object.values(choices),addresses])n.oninput=()=>{status.textContent=mode()==='tailnet'&&['unavailable','not_signed_in','problem'].includes(current?.tailnet?.state)?'Not set up · '+current.tailnet.message:'Unsaved change';draw();};dialog?.addEventListener('close',()=>{closed=true;},{once:true});void update();
}
export function mountLocalServer(root,{nativeInvoke,workingBots=()=>0,dialog}){
 const status=el('p','local-server-status','Checking local server…');status.setAttribute('role','status');const versions=el('p','muted'),impact=el('p','muted','Updating or repairing interrupts active bot work and computer sessions.'),progress=el('progress'),details=el('details'),summary=el('summary','','Progress details'),log=el('pre');details.append(summary,log);
 const actions=el('div','row-actions'),update=button('Update local server',()=>start()),trouble=el('details'),troubleTitle=el('summary','','Troubleshooting'),repair=button('Repair local server',()=>start());trouble.append(troubleTitle,repair);actions.append(update);root.append(status,versions,impact,progress,details,actions,trouble);
 let closed=false,polling=false,starting=false,timer,current=null,lastVersion='',epoch=0;
 function draw(value){current=value;const working=starting||value.status==='working',pending=value.status==='awaiting_restart',server=value.local_server;
  if(server){lastVersion=server.version;versions.textContent=`Desktop app ${server.desktop_version} · Local server ${server.version}`;}
  status.textContent=pending?'Update ready · restart the local server to apply.':working?(value.stage||'Local server restarting · reconnecting…'):value.status==='error'?(value.message||'Local server needs attention.'):server?.update_available?'A local server update is available.':value.status==='ready'&&lastVersion?'Updated to '+lastVersion:server?'Local server is up to date.':value.message||'Local server is offline. Use Repair to start it again.';
  status.setAttribute('role',value.status==='error'?'alert':'status');progress.hidden=!working;progress.max=value.stage_count||5;if(Number.isFinite(value.completed_stages))progress.value=value.completed_stages;else progress.removeAttribute('value');log.textContent=value.detail||'';details.hidden=!value.detail;update.textContent=pending?'Restart local server':'Update local server';update.hidden=!server?.update_available&&!working&&!pending;update.disabled=working;repair.disabled=working||pending;impact.hidden=!working&&!pending&&!server?.update_available;
 }
 async function poll(){if(closed||polling)return;polling=true;const version=epoch;try{const value=await nativeInvoke('standalone_status',{});if(!closed&&version===epoch)draw(value);}catch(e){if(!closed){status.textContent=(current?.status==='working'?'Local server restarting · reconnecting…':'Could not check local server. Retrying…');}}finally{polling=false;if(!closed)timer=setTimeout(poll,current?.status==='working'?1000:5000);}}
 async function start(){if(starting||current?.status==='working'||closed)return;const count=workingBots();if(!confirm(`This interrupts active bot work and computer sessions.${count?' '+count+' bot'+(count===1?' is':'s are')+' working.':''} Continue?`))return;
  const command=current?.status==='awaiting_restart'?'restart_local_server':'prepare_local_server';epoch++;starting=true;draw({...current,status:'working',stage:command==='restart_local_server'?'Local server restarting · reconnecting…':'Preparing local server…'});try{await nativeInvoke(command,{});}catch(e){if(!closed)draw({status:'error',message:e.message||String(e)});}finally{starting=false;clearTimeout(timer);void poll();}}
 dialog?.addEventListener('close',()=>{closed=true;clearTimeout(timer);},{once:true});void poll();
}
