const el=(tag,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
const button=(text,action)=>{const b=el('button','outline-button',text);b.type='button';b.onclick=action;return b;};
export function isLocalStandalone(){return !!window.__KINDRED_PROFILE_HOST&&location.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(location.hostname)&&location.port==='9444';}
export function mountPhoneAccess(root,{nativeInvoke,onPair,workingBots=()=>0,dialog}){
 const form=el('form','standalone-access'),currently=el('p','access-current','Currently: checking access…'),otherComputer=el('p','muted','On another computer, open this address in Kindred → Add account, or in a browser.'),group=el('fieldset');group.append(el('legend','','Who can reach this Kindred'));
 const choices={};for(const [value,name,help] of [['local','Only this computer','Kindred is only reachable on this computer (http://127.0.0.1:9444).'],['tailnet','My devices with Tailscale (recommended)','Your other computers, laptops and phones open this same workspace from anywhere while Tailscale is on. Encrypted and private to your Tailscale network.'],['lan','Advanced: choose networks','Pick exactly which networks can reach Kindred. Unencrypted choices need your confirmation.']]){const label=el('label','access-choice'),radio=el('input');radio.type='radio';radio.name='standalone-access';radio.value=value;label.append(radio,el('strong','',name),el('span','muted',help));choices[value]=radio;group.append(label);}
 const setup=el('div','tailnet-setup'),steps=el('ol');for(const text of ['Install Tailscale on this computer and your devices, then sign in to the same Tailscale network.','Enable MagicDNS and HTTPS certificates in your Tailscale admin settings.','Save your choice below. Keep this computer awake.'])steps.append(el('li','',text));const guide=el('a','','Tailscale setup instructions');guide.href='https://tailscale.com/docs/features/tailscale-serve';guide.target='_blank';guide.rel='noopener noreferrer';setup.append(steps,guide);
 const networks=el('section','network-selection'),search=el('input'),count=el('p','muted'),limit=el('p','profile-form-error'),list=el('div','network-list'),others=el('details','network-other'),otherList=el('div','network-list');search.type='search';search.placeholder='Search networks';search.setAttribute('aria-label','Search networks');others.append(el('summary','','Other networks'),otherList);
 const shareRow=el('label','network-row'),share=el('input');share.type='checkbox';shareRow.append(share,el('strong','','Tailscale HTTPS · encrypted · recommended'));
 const allLabel=el('label','network-row'),all=el('input');all.type='checkbox';allLabel.append(all,el('span','','All networks, including ones added later'));networks.append(el('p','muted','Always available on this computer at http://127.0.0.1:9444'),shareRow,search,count,list,others,allLabel);
 const advanced=el('details');advanced.append(el('summary','','Additional connection addresses'),el('p','muted','localhost and 127.0.0.1 both mean this computer. Use complete addresses. HTTP choices need your confirmation.'));const addresses=el('textarea');addresses.rows=3;addresses.setAttribute('aria-label','Additional connection addresses');advanced.append(addresses);
 const connections=el('section','connection-addresses'),tailAddress=el('section','tailnet-address'),status=el('p','access-status','Checking access…'),error=el('p','profile-form-error');status.setAttribute('role','status');status.tabIndex=-1;error.setAttribute('role','alert');
 const check=button('Check again',()=>update()),actions=el('div','row-actions access-save-bar'),unsaved=el('span','muted','Unsaved changes'),save=button('Save',()=>apply()),discard=button('Discard changes',()=>{restore();status.textContent='Changes discarded.';draw();});save.classList.add('primary');actions.append(unsaved,save,discard);
 const phone=el('section','access-phone'),pair=button('Connect mobile app',()=>{if(canLeave())onPair();}),pairHelp=el('p','muted');phone.append(el('h3','','Phone app'),el('p','muted','After access works, you can pair the Kindred phone app.'),pairHelp,pair);
 form.append(currently,otherComputer,group,setup,networks,advanced,connections,tailAddress,status,limit,error,check,actions,phone);root.append(form);form.onsubmit=e=>e.preventDefault();
 let current=null,busy=false,closed=false,selected=new Set(),wantAll=false,wantTailnet=false,confirmation=null,currentUnknown=false;const mode=()=>Object.keys(choices).find(k=>choices[k].checked)||'local',values=()=>addresses.value.split('\n').map(v=>v.trim()).filter(Boolean),wantsShare=()=>mode()==='tailnet'||mode()==='lan'&&wantTailnet;
 const sorted=a=>JSON.stringify([...new Set(a)].sort()),newAllOrigins=()=>{try{return mode()==='lan'&&wantAll&&sorted(proposed())!==sorted(current?.active_origins||current?.addresses||[]);}catch{return true;}},dirty=()=>!!current&&(current.pending||current.needs_reconcile||newAllOrigins()||mode()!==current.access||sorted(values())!==sorted(current.extra_addresses||[])||mode()==='lan'&&(wantAll!==!!current.all_networks||wantTailnet!==!!current.tailnet_https||sorted([...selected])!==sorted(current.selected_interfaces||[])||current.interfaces?.some(r=>selected.has(r.id)&&r.address_changed)));
 function restore(){if(!current)return;choices[current.access||'local'].checked=true;addresses.value=(current.extra_addresses||[]).join('\n');selected=new Set(current.selected_interfaces||[]);wantAll=!!current.all_networks;wantTailnet=!!current.tailnet_https;}
 function usable(ip){return !/^(127\.|0\.|169\.254\.|22[4-9]\.|23[0-9]\.)/.test(ip)&&!/^(::(?:1)?$|fe[89ab][0-9a-f]:|ff)/i.test(ip);}
 function privateLiteral(value){try{const h=new URL(value).hostname.replace(/^\[|\]$/g,'');return h.includes(':')?/^fd[0-9a-f]{2}:/i.test(h):/^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.|100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.)/.test(h);}catch{return false;}}
 function addressOrigin(v){const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('Use complete HTTP or HTTPS addresses without a path or credentials.');return u.origin;}
 function privateNetwork(v){try{const h=new URL(v).hostname;return privateLiteral(v)||/^\[fc[0-9a-f]{2}:/i.test(h)||h==='localhost'||/^127\./.test(h)||h==='[::1]'||h.endsWith('.ts.net')||h.endsWith('.local');}catch{return false;}}
 function proposed(){const result=new Set(mode()!=='lan'?[]:values().map(addressOrigin));if(mode()==='lan')for(const row of current?.interfaces||[])if(row.available&&(wantAll||selected.has(row.id)))for(const ip of row.addresses)if(usable(ip))result.add('http://'+(ip.includes(':')?'['+ip+']':ip)+':9444');if(mode()==='lan'&&current?.tailnet?.browser_address&&(wantAll||(current.interfaces||[]).some(r=>r.kind==='tailnet'&&selected.has(r.id))))result.add(current.tailnet.browser_address);if(wantsShare()&&current?.tailnet?.address)result.add(current.tailnet.address);return [...result].sort();}
 async function copyAddress(value){try{await navigator.clipboard.writeText(value);status.textContent='Address copied.';}catch{error.textContent='Could not copy the address. Select it and copy it manually.';}}
 function renderNetworks(){const focus=document.activeElement?.dataset.networkId;list.replaceChildren();otherList.replaceChildren();const query=search.value.toLowerCase(),rows=[...(current?.interfaces||[])];for(const id of selected)if(!rows.some(r=>r.id===id))rows.push({id,name:'Other',kind:'other',available:false,addresses:[]});let found=0;for(const row of rows){if(![row.id,row.name,...row.addresses].join(' ').toLowerCase().includes(query))continue;found++;const label=el('label','network-row'),box=el('input'),body=el('span','network-row-body');box.type='checkbox';box.dataset.networkId=row.id;box.checked=selected.has(row.id);box.disabled=busy||!current?.connection_access_supported||wantAll||!row.available&&!box.checked;box.onchange=()=>{if(box.checked)selected.add(row.id);else selected.delete(row.id);changed();};body.append(el('strong','',row.name),el('span','muted',row.id),el('span','network-addresses',row.addresses.join(' · ')),el('span','network-badge',row.kind==='tailnet'?'Tailscale · private':row.kind==='lan'?'Local network':'Usually not reachable from your phone'));if(!row.available)body.append(el('span','profile-form-error','Not available right now'));if(row.address_changed)body.append(el('span','profile-form-error','Address changed · save to use the new address'));for(const ip of row.addresses)if(usable(ip)&&!privateLiteral('http://'+(ip.includes(':')?'['+ip+']':ip)+':9444')&&!/^fc[0-9a-f]{2}:/i.test(ip))body.append(el('span','profile-form-error','Public address · unencrypted access requires your confirmation'));label.append(box,body);(row.kind==='other'?otherList:list).append(label);}count.textContent=found+' of '+rows.length+' networks';others.hidden=!otherList.childElementCount;if(query)others.open=true;if(focus)list.querySelectorAll('input').forEach(n=>{if(n.dataset.networkId===focus&&!n.disabled)n.focus({preventScroll:true});});}
 function draw(){const supported=!!current?.connection_access_supported&&current?.connection_access_server_supported!==false;const active=current?.applied_addresses??[...(current?.connection_addresses||[]).filter(r=>r.state==='listening').map(r=>r.address),...(current?.tailnet_address_ready&&current?.tailnet?.address?[current.tailnet.address]:[])];currently.textContent=active.length?'Currently: '+active.map(v=>v+(v.startsWith('https:')?' (encrypted)':' (not encrypted)')).join(' and ')+'.':!current?.sharing_unknown&&current?.active_bindings?.length&&current.active_bindings.every(v=>['127.0.0.1','::1'].includes(v))?'Currently: only this computer.':'Currently: access could not be confirmed.';otherComputer.hidden=!active.length||currentUnknown;otherComputer.textContent=active.length?'On another computer, open '+active.join(' or ')+' in Kindred → Add account, or in a browser.':'';if(currentUnknown)currently.textContent='Currently: access could not be confirmed.';if(current?.sharing_unknown)currently.textContent+=' '+(current.tailnet?.state==='problem'&&current.tailnet.message?current.tailnet.message:'Tailscale access could not be confirmed.');setup.hidden=!wantsShare();networks.hidden=mode()!=='lan';advanced.hidden=mode()!=='lan';share.checked=wantTailnet;share.disabled=busy||!supported;search.disabled=busy;all.checked=wantAll;all.disabled=busy||!supported;for(const n of [...Object.values(choices),addresses])n.disabled=busy||!supported;
  let reason='';try{if(proposed().length>8)reason='Kindred can allow up to 8 connection addresses. Deselect a network or remove an additional address.';}catch{reason='Enter complete HTTP or HTTPS connection addresses.';}if(wantsShare()&&!['shared','not_set_up'].includes(current?.tailnet?.state))reason=current?.tailnet?.message||'Set up Tailscale first, then check again.';if(current?.connection_access_server_supported===false)reason='Update the local server to change connection access here. Your current settings stay as they are.';if(current&&!current.connection_access_supported)reason='Update the Kindred desktop app to change connection access here. Your current settings stay as they are.';if(currentUnknown)reason='Check again to confirm current access before saving.';limit.textContent=reason;actions.hidden=!dirty()&&supported;save.disabled=busy||!supported||!dirty()||!!reason;discard.disabled=busy||!supported;unsaved.hidden=!supported;form.classList.toggle('access-read-only',!supported);unsaved.textContent=busy?'Applying changes…':'Unsaved changes';check.disabled=busy;
  tailAddress.replaceChildren();if(current?.tailnet?.address&&(wantsShare()||current.tailnet.state==='shared')){if(current.tailnet_address_ready&&!currentUnknown){const card=el('div','connection-address');card.append(el('code','',current.tailnet.address),el('span','network-badge','Encrypted · Tailscale HTTPS'),el('span','muted','Works with the phone app'),el('span','muted','Listening'),button('Copy address',()=>copyAddress(current.tailnet.address)));tailAddress.append(card);}else tailAddress.append(el('p','',current.tailnet.state==='shared'?'Tailscale sharing is on · access is not confirmed yet.':'Will be: '+current.tailnet.address));}
  connections.replaceChildren();for(const row of current?.connection_addresses||[]){const item=el('div','connection-address');item.append(el('code','',row.address),el('span','network-badge',row.kind==='tailnet'?'Private to your Tailscale devices · not HTTPS':'Not encrypted'),el('span','muted',row.phone_capable?'Works with the updated phone app':'Desktop browsers only'),el('span','muted',row.state==='listening'?'Listening':row.state==='saved'?'Saved · not active yet':"Couldn't listen here: "+(row.error||'Check this address.')));if(row.state==='listening')item.append(button('Copy address',()=>copyAddress(row.address)));connections.append(item);}
  const capable=current?.tailnet_address_ready||current?.connection_addresses?.some(r=>r.state==='listening'&&r.phone_capable);pair.disabled=busy||!capable||currentUnknown;pairHelp.textContent=capable?'Opens this same workspace on your phone.':'Save an access option first.';renderNetworks();
 }
 function changed(){status.textContent='';draw();}
 async function update(){if(busy||closed)return;busy=true;error.textContent='';draw();try{const value=await nativeInvoke('standalone_network',{});if(closed)return;const initial=!current;current=value;currentUnknown=false;if(initial)restore();draw();}catch(e){if(!closed){currentUnknown=true;error.textContent=e.message||String(e);}}finally{busy=false;if(!closed)draw();}}
 function needsRestart(next){const bindings=mode()==='lan'?(wantAll?['0.0.0.0']:['127.0.0.1',...(current?.interfaces||[]).filter(r=>selected.has(r.id)&&r.available).flatMap(r=>r.addresses).filter(usable)]):['127.0.0.1'];return !!current.pending||sorted(next)!==sorted(current.active_origins||[])||sorted(bindings)!==sorted((current.active_bindings||[]).filter(v=>v!=='::'||!wantAll));}
 async function confirmSave(next){const http=next.filter(v=>v.startsWith('http:')),d=el('dialog','settings-dialog access-confirm');d.setAttribute('aria-label','Confirm connection access');const body=el('section','settings-main'),buttons=el('div','row-actions');body.append(el('h2','','Confirm connection access'));if(http.length)body.append(el('p','','This will enable access over unsecure HTTP, are you sure you want to do this?'));else body.append(el('p','',wantsShare()?'Kindred will be shared privately with your Tailscale devices.':"Kindred's Tailscale sharing will be turned off. Your other devices won't reach this Kindred. Other Tailscale shares stay as they are."));const rows=el('ul');for(const a of next)rows.append(el('li','',a));body.append(rows);if(http.length)body.append(el('p','','Sign-ins and conversations on these networks are not encrypted.'));if(http.some(v=>!privateNetwork(v)))body.append(el('p','','Includes a public address: anyone on the internet who can reach this computer could try to connect.'));if(current.active_bindings?.includes('0.0.0.0')&&(!wantAll||mode()!=='lan'))body.append(el('p','',"Kindred will stop accepting connections on networks you didn't select."));if(wantAll&&mode()==='lan')body.append(el('p','','Kindred will listen on every network this computer joins, including ones added later.'));const count=workingBots(),restartNeeded=needsRestart(next);if(restartNeeded)body.append(el('p','',`Kindred restarts briefly to apply this.${count?' '+count+' bot'+(count===1?' is':'s are')+' working and will be interrupted.':''}`));let accepted=false;const yes=button(restartNeeded?(http.length?'Allow HTTP and restart':'Save and restart'):http.length?'Allow unsecure HTTP':'Save',()=>{accepted=true;d.close();}),no=button('Cancel',()=>d.close());yes.classList.add('primary');buttons.append(no,yes);body.append(buttons);d.append(body);document.body.append(d);confirmation=d;return new Promise(resolve=>{d.addEventListener('close',()=>{d.remove();confirmation=null;resolve(accepted);},{once:true});d.showModal();no.focus();});}
 async function apply(){if(busy||closed||confirmation||save.disabled)return;const next=proposed();if(!await confirmSave(next)||closed)return;busy=true;error.textContent='';status.textContent='Saving…';draw();let timer;const progress=async()=>{if(!busy||closed)return;try{const v=await nativeInvoke('standalone_status',{});if(busy&&!closed&&v.status==='working'&&v.stage)status.textContent=v.stage;}catch{}if(busy&&!closed)timer=setTimeout(progress,750);};void progress();try{current=await nativeInvoke('standalone_network',{applyAccess:true,access:mode(),addresses:mode()==='lan'?values():[],interfaces:mode()==='lan'&&!wantAll?[...selected]:[],allNetworks:mode()==='lan'&&wantAll,tailnetHttps:wantsShare(),confirmedHttpOrigins:next.filter(v=>v.startsWith('http:'))});if(closed)return;currentUnknown=false;restore();const ready=[...(current.tailnet_address_ready?[current.tailnet.address]:[]),...(current.connection_addresses||[]).filter(r=>r.state==='listening').map(r=>r.address)];status.textContent=ready.length?'Saved. '+(current.tailnet_address_ready?'Shared at '+current.tailnet.address+' through Tailscale. ':'')+(ready.filter(v=>v.startsWith('http:')).length?'Kindred is now listening at '+ready.filter(v=>v.startsWith('http:')).join(' and ')+'.':''):current.pending||current.needs_reconcile||current.sharing_unknown?'Saved settings, but access is not confirmed yet. Check Currently before trying again.':'Saved. Kindred is listening on this computer.';}catch(e){if(!closed){error.textContent=e.message||String(e);status.textContent='Could not apply all changes. Checking current access…';try{current=await nativeInvoke('standalone_network',{});currentUnknown=false;}catch{currentUnknown=true;}status.textContent='Some changes may not have been applied. Check Currently before trying again.';}}finally{busy=false;clearTimeout(timer);if(!closed){draw();status.focus();}}}
 all.onchange=()=>{wantAll=all.checked;if(wantAll)selected.clear();changed();};share.onchange=()=>{wantTailnet=share.checked;changed();};search.oninput=renderNetworks;for(const n of Object.values(choices))n.oninput=()=>{if(n.value==='lan'&&current?.access!=='lan')wantTailnet=false;changed();};addresses.oninput=changed;dialog?.addEventListener('cancel',e=>{if(!canLeave())e.preventDefault();});dialog?.addEventListener('close',()=>{closed=true;confirmation?.close();},{once:true});const observer=typeof ResizeObserver==='function'?new ResizeObserver(()=>{form.style.paddingBottom=actions.hidden||form.classList.contains('access-read-only')?'0px':(actions.getBoundingClientRect().height+16)+'px';}):null;observer?.observe(actions);dialog?.addEventListener('close',()=>observer?.disconnect(),{once:true});void update();return {canLeave};
 function canLeave(){if(busy){error.textContent='Wait for connection access to finish changing.';return false;}if(dirty()&&!confirm('Discard your changes?'))return false;restore();draw();return true;}
}

export function mountLocalServer(root,{nativeInvoke,workingBots=()=>0,dialog}){
 const status=el('p','local-server-status','Checking local server…');status.setAttribute('role','status');const versions=el('p','muted'),impact=el('p','muted','Updating or repairing interrupts active bot work and computer sessions.'),progress=el('progress'),details=el('details'),summary=el('summary','','Progress details'),log=el('pre');details.append(summary,log);
 const actions=el('div','row-actions'),update=button('Update local server',()=>start()),trouble=el('details'),troubleTitle=el('summary','','Troubleshooting'),repair=button('Repair local server',()=>start());trouble.append(troubleTitle,repair);actions.append(update);root.append(status,versions,impact,progress,details,actions,trouble);
 let closed=false,polling=false,starting=false,timer,current=null,lastVersion='',epoch=0;
 function draw(value){current=value;const working=starting||value.status==='working',pending=value.status==='awaiting_restart',server=value.local_server;
  if(server){lastVersion=server.version;versions.textContent=`Desktop app ${server.desktop_version} · Local server ${server.version}`;}
  status.textContent=pending?'Update ready · restart the local server to apply.':working?(value.stage||'Local server restarting · reconnecting…'):value.status==='error'?(value.message||'Local server needs attention.'):server?.update_available?'A local server update is available.':value.status==='ready'&&lastVersion?'Updated to '+lastVersion:server?'Local server is up to date.':value.message||'Local server is offline. Use Repair to start it again.';
  status.setAttribute('role',value.status==='error'?'alert':'status');progress.hidden=!working;progress.max=value.stage_count||5;if(Number.isFinite(value.completed_stages))progress.value=value.completed_stages;else progress.removeAttribute('value');log.textContent=value.detail||'';details.hidden=!value.detail;update.textContent=pending?'Restart local server':'Update local server';update.hidden=!server?.update_available&&!working&&!pending;update.disabled=working;repair.disabled=working||pending;impact.hidden=!working&&!pending&&!server?.update_available;
 }
 async function poll(){if(closed||polling)return;polling=true;const version=epoch;try{const value=await nativeInvoke('standalone_status',{});if(!closed&&version===epoch)draw(value);}catch(e){if(!closed){status.textContent=(current?.status==='working'?'Local server restarting · reconnecting…':'Could not check local server. Retrying…');}}finally{polling=false;if(!closed)timer=setTimeout(poll,current?.status==='working'?1000:5000);}}
 async function start(){if(starting||current?.status==='working'||closed)return;const count=workingBots();if(!confirm(`This interrupts active bot work and computer sessions.${count?' '+count+' bot'+(count===1?' is':'s are')+' working.':''} Continue?`))return;
  const command=current?.status==='awaiting_restart'?'restart_local_server':'prepare_local_server';epoch++;starting=true;draw({...current,status:'working',stage:command==='restart_local_server'?'Local server restarting · reconnecting…':'Preparing local server…'});try{await nativeInvoke(command,{});}catch(e){if(!closed)draw({status:'error',message:e.message||String(e)});}finally{starting=false;clearTimeout(timer);void poll();}}
 dialog?.addEventListener('close',()=>{closed=true;clearTimeout(timer);},{once:true});void poll();
}
