const el=(tag,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
const button=(text,action)=>{const b=el('button','outline-button',text);b.type='button';b.onclick=action;return b;};
export function isLocalStandalone(){return !!window.__KINDRED_PROFILE_HOST&&location.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(location.hostname)&&location.port==='9444';}
export function mountPhoneAccess(root,{nativeInvoke,onPair,workingBots=()=>0,dialog}){
 const form=el('form','standalone-access'),group=el('fieldset');group.append(el('legend','','Who can reach this Kindred'));
 const choices={};for(const [value,name,help] of [['local','Only this computer','Kindred is only reachable on this computer.'],['tailnet','My devices with Tailscale (recommended)','Your phone opens this same workspace from anywhere while Tailscale is on.'],['lan','Advanced: local network','Choose which networks Kindred listens on. For your phone, My devices with Tailscale is simpler and uses HTTPS.']]){const label=el('label','access-choice'),radio=el('input');radio.type='radio';radio.name='standalone-access';radio.value=value;label.append(radio,el('strong','',name),el('span','muted',help));choices[value]=radio;group.append(label);}
 const setup=el('div','tailnet-setup'),steps=el('ol');for(const text of ['Install Tailscale on this computer and your phone, then sign in to the same Tailscale network.','Enable MagicDNS and HTTPS certificates in your Tailscale admin settings.','Turn on phone access below. Keep this computer awake.'])steps.append(el('li','',text));const guide=el('a','','Tailscale setup instructions');guide.href='https://tailscale.com/docs/features/tailscale-serve';guide.target='_blank';guide.rel='noopener noreferrer';setup.append(steps,guide);
 const networks=el('section','network-selection'),search=el('input'),count=el('p','muted'),limit=el('p','profile-form-error'),list=el('div','network-list'),others=el('details','network-other'),otherList=el('div','network-list');search.type='search';search.placeholder='Search networks';search.setAttribute('aria-label','Search networks');others.append(el('summary','','Other networks'),otherList);
 const allLabel=el('label','network-row'),all=el('input');all.type='checkbox';allLabel.append(all,el('span','','All networks, including ones added later'));
 networks.append(el('p','muted','Always available on this computer at http://127.0.0.1:9444'),search,count,limit,list,others,allLabel);
 const connections=el('section','connection-addresses'),sharing=el('p','tailnet-sharing');
 const advanced=el('details'),summary=el('summary','','Additional connection addresses');advanced.append(summary,el('p','muted','localhost and 127.0.0.1 both mean this computer. Use complete addresses. Public browser connections over HTTP are not enabled.'));
 const addresses=el('textarea');addresses.rows=3;addresses.setAttribute('aria-label','Additional connection addresses');advanced.append(addresses);
 const phone=el('div','phone-address'),phoneLabel=el('span'),address=el('code'),copy=button('Copy address',()=>copyAddress(address.textContent));phone.append(phoneLabel,address,el('span','muted','Works with the phone app'),copy);
 const status=el('p','access-status','Checking phone access…');status.setAttribute('role','status');status.tabIndex=-1;const error=el('p','profile-form-error');error.setAttribute('role','alert');
 const actions=el('div','row-actions'),check=button('Check again',()=>update()),save=button('Save',()=>update(saveArgs())),enable=button('Turn on phone access',()=>update({access:'tailnet',addresses:values(),enableTailnet:true})),pair=button('Connect mobile app',onPair),restart=button('Restart Kindred',async()=>{const n=workingBots();if(!confirm(`Restarting stops active bot work and computer sessions for a short time.${n?' '+n+' bot'+(n===1?' is':'s are')+' working.':''}${publicExposure()?' '+publicWarning:''} Restart now?`))return;await update({restart:true});}),disable=button('Turn off phone access',()=>update({disableTailnet:true}));actions.append(check,save,enable,disable,restart,pair);
 const impact=el('p','muted access-impact','Saving does not restart Kindred. Restart when your bots have finished their work.');form.append(group,setup,networks,advanced,connections,sharing,phone,status,error,impact,actions);root.append(form);form.onsubmit=e=>e.preventDefault();
 const publicWarning='Kindred will listen on a public address without encryption. Browsers are blocked, but apps with a valid sign-in could still connect over HTTP.';
 let current=null,busy=false,closed=false,selected=new Set(),wantAll=false;const mode=()=>Object.keys(choices).find(k=>choices[k].checked)||'local',values=()=>addresses.value.split('\n').map(v=>v.trim()).filter(Boolean);
 const dirty=()=>current&&(mode()!==current.access||JSON.stringify(values())!==JSON.stringify(current.extra_addresses||current.addresses||[])||mode()==='lan'&&(wantAll!==!!current.all_networks||JSON.stringify([...selected].sort())!==JSON.stringify([...(current.selected_interfaces||[])].sort())||current.interfaces?.some(r=>selected.has(r.id)&&r.address_changed)));
 function saveArgs(){const args={access:mode(),addresses:values()};if(mode()==='lan'&&current?.interface_selection_supported){args.interfaces=wantAll?[]:[...selected];args.allNetworks=wantAll;}return args;}
 async function copyAddress(value){try{await navigator.clipboard.writeText(value);status.textContent='Address copied.';}catch{error.textContent='Could not copy the address. Select it and copy it manually.';}}
 function privateLiteral(value){try{const u=new URL(value),h=u.hostname.replace(/^\[|\]$/g,'');return h.includes(':')?/^fd[0-9a-f]{2}:/i.test(h):/^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.|100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.)/.test(h);}catch{return false;}}
 function publicExposure(){return (current?.interfaces||[]).filter(r=>r.available&&(wantAll||selected.has(r.id))).some(row=>row.addresses.some(ip=>{if(/^(127\.|0\.|169\.254\.|22[4-9]\.|23[0-9]\.)/.test(ip)||/^(::|fe[89ab][0-9a-f]:|ff|fc[0-9a-f]{2}:)/i.test(ip))return false;return !privateLiteral('http://'+(ip.includes(':')?'['+ip+']':ip)+':9444');}));}
 function addressCount(){const result=new Set(values().map(v=>{try{return new URL(v).origin;}catch{return v;}}));if(mode()==='lan'){const rows=(current?.interfaces||[]).filter(r=>r.available&&(wantAll||selected.has(r.id)));for(const row of rows)for(const ip of row.addresses){const value='http://'+(ip.includes(':')?'['+ip+']':ip)+':9444';if(privateLiteral(value)||/^fc[0-9a-f]{2}:/i.test(ip))result.add(value);}if(rows.some(r=>r.kind==='tailnet')&&current.tailnet?.browser_address)result.add(current.tailnet.browser_address);}return result.size;}
 function renderNetworks(){const focused=document.activeElement?.dataset.networkId;list.replaceChildren();otherList.replaceChildren();const query=search.value.toLowerCase(),rows=[...(current?.interfaces||[])];for(const id of selected)if(!rows.some(r=>r.id===id))rows.push({id,name:'Other',kind:'other',available:false,addresses:[]});let found=0;
  for(const row of rows){if(![row.id,row.name,...row.addresses].join(' ').toLowerCase().includes(query))continue;found++;const label=el('label','network-row'),box=el('input'),body=el('span','network-row-body');box.type='checkbox';box.dataset.networkId=row.id;box.checked=selected.has(row.id);box.disabled=busy||wantAll||!row.available&&!box.checked;box.onchange=()=>{if(box.checked)selected.add(row.id);else selected.delete(row.id);changed();};body.append(el('strong','',row.name),el('span','muted',row.id),el('span','network-addresses',row.addresses.join(' · ')),el('span','network-badge',row.kind==='tailnet'?'Tailscale · private':row.kind==='lan'?'Local network':'Usually not reachable from your phone'));
   if(!row.available)body.append(el('span','profile-form-error','Not available right now'));if(row.address_changed)body.append(el('span','profile-form-error','Address changed · save to use the new address'));for(const ip of row.addresses){if(/^fe[89ab][0-9a-f]:/i.test(ip)||ip.startsWith('169.254.'))continue;if(/^fc[0-9a-f]{2}:/i.test(ip)){body.append(el('span','muted','Desktop browsers only'));continue;}if(!privateLiteral('http://'+(ip.includes(':')?'['+ip+']':ip)+':9444'))body.append(el('span','profile-form-error',"Public address · browser connections over HTTP aren't enabled"));}
   label.append(box,body);(row.kind==='other'?otherList:list).append(label);
  }count.textContent=found+' of '+rows.length+' networks';others.hidden=!otherList.childElementCount;if(query)others.open=true;if(focused){const box=[...networks.querySelectorAll('input[type=checkbox]')].find(n=>n.dataset.networkId===focused);if(box&&!box.disabled)box.focus({preventScroll:true});}
 }
 function renderConnections(){connections.replaceChildren();for(const row of current?.connection_addresses||[]){const item=el('div','connection-address'),code=el('code','',row.address);item.append(code,el('span','network-badge',row.kind==='tailnet'?'Private to your Tailscale devices · not HTTPS':'Not encrypted'),el('span','muted',row.phone_capable?'Works with the updated phone app':'Desktop browsers only'));if(row.state==='listening')item.append(el('span','', 'Listening on '+row.address));else if(row.state==='saved')item.append(el('span','muted','Saved · restart Kindred to apply'));if(row.error)item.append(el('span','profile-form-error',row.error));if(row.state==='listening')item.append(button('Copy address',()=>copyAddress(row.address)));connections.append(item);}}
 function draw(){const tailnet=mode()==='tailnet',lan=mode()==='lan';sharing.hidden=!lan||current?.tailnet?.state!=='shared'||!current?.tailnet?.address;sharing.textContent=sharing.hidden?'':'Tailscale HTTPS sharing is still on · '+current.tailnet.address;impact.hidden=!current?.pending;setup.hidden=!tailnet;networks.hidden=!lan;search.disabled=busy;all.checked=wantAll;all.disabled=busy||!current?.interface_selection_supported;advanced.hidden=mode()==='local';connections.hidden=!lan;phone.hidden=!tailnet||!current?.tailnet?.address;address.textContent=current?.tailnet?.address||'';phoneLabel.textContent=current?.ready_to_pair?'Phone address: ':'Will be: ';copy.hidden=!current?.ready_to_pair;save.hidden=tailnet;limit.textContent=addressCount()>8?'Kindred can allow up to 8 connection addresses. Deselect a network or remove an additional address.':'';save.disabled=busy||!dirty()||!!limit.textContent||lan&&!current?.interface_selection_supported;enable.hidden=!tailnet||!!current?.ready_to_pair||!!current?.pending;enable.disabled=busy||!current||!['shared','not_set_up'].includes(current.tailnet?.state);restart.hidden=!current?.pending;restart.disabled=busy||!current||dirty();disable.hidden=current?.tailnet?.state!=='shared';disable.disabled=busy;pair.hidden=!current?.ready_to_pair&&!current?.tailnet_address_ready&&!(lan&&!current?.pending&&current?.connection_addresses?.some(r=>r.phone_capable&&r.state==='listening'));pair.disabled=busy;check.disabled=busy;for(const n of [...Object.values(choices),addresses])n.disabled=busy;renderNetworks();renderConnections();if(lan&&current&&!current.interface_selection_supported)count.textContent='Update the desktop app to choose individual networks. Your existing network settings are retained.';}
 function changed(){status.textContent=mode()==='tailnet'&&['unavailable','not_signed_in','problem'].includes(current?.tailnet?.state)?'Not set up · '+current.tailnet.message:'Unsaved change';draw();}
 async function update(args={}){if(busy||closed)return;busy=true;error.textContent='';status.textContent=args.enableTailnet?'Setting up private phone access…':args.restart?'Local server restarting · reconnecting…':'Checking phone access…';draw();try{const value=await nativeInvoke('standalone_network',args);if(closed)return;const initial=!current;current=value;if(initial||Object.keys(args).length){choices[value.access||'local'].checked=true;addresses.value=(value.extra_addresses||value.addresses||[]).join('\n');selected=new Set(value.selected_interfaces||[]);wantAll=value.all_networks===undefined?value.bind==='0.0.0.0':!!value.all_networks;}
   status.textContent=value.pending?(mode()==='tailnet'?'Needs restart · Saved — restart Kindred to apply.':'Saved · restart Kindred to apply')+(value.active_bindings?.includes('0.0.0.0')&&!value.all_networks?". Kindred will stop accepting connections on networks you didn't select.":''):value.tailnet?.state==='problem'&&mode()==='tailnet'?'Problem · '+value.tailnet.message:value.ready_to_pair?'Ready to pair · Opens this same workspace on your phone':value.tailnet?.state==='shared'&&mode()==='local'?'Tailscale is still sharing this Kindred with your devices.':mode()==='tailnet'?(value.tailnet?.message||'Not set up'):value.access==='lan'?(value.connection_addresses?.some(r=>r.state==='listening')?'Listening on '+value.connection_addresses.filter(r=>r.state==='listening').map(r=>{try{return new URL(r.address).hostname;}catch{return r.address;}}).join(' and '):value.connection_addresses?.length?'Problem · Check the connection addresses below.':'Choose networks below.'):'Off · Kindred listens on this computer only.';if(value.interface_error&&mode()==='lan')error.textContent=value.interface_error;
  }catch(e){if(!closed){status.textContent='Problem';error.textContent=e.message||String(e);}}finally{busy=false;if(!closed){draw();if(Object.keys(args).length)status.focus();}}}
 all.onchange=()=>{if(all.checked&&!confirm('Kindred will accept connections on every network this computer joins.'+((current?.interfaces||[]).some(r=>r.addresses.some(ip=>!privateLiteral('http://'+(ip.includes(':')?'['+ip+']':ip)+':9444')&&!/^(fe[89ab][0-9a-f]:|fc[0-9a-f]{2}:|169\.254\.)/i.test(ip)))?' '+publicWarning:'')+' Turn on All networks?')){all.checked=false;return;}wantAll=all.checked;if(wantAll)selected.clear();changed();};search.oninput=()=>renderNetworks();for(const n of [...Object.values(choices),addresses])n.oninput=changed;dialog?.addEventListener('close',()=>{closed=true;},{once:true});void update();
}
export function mountLocalServer(root,{nativeInvoke,workingBots=()=>0,dialog}){
 const status=el('p','local-server-status','Checking local server…');status.setAttribute('role','status');const versions=el('p','muted'),impact=el('p','muted','Updating or repairing interrupts active bot work and computer sessions.'),progress=el('progress'),details=el('details'),summary=el('summary','','Progress details'),log=el('pre');details.append(summary,log);
 const actions=el('div','row-actions'),update=button('Update local server',()=>start()),trouble=el('details'),troubleTitle=el('summary','','Troubleshooting'),repair=button('Repair local server',()=>start());trouble.append(troubleTitle,repair);actions.append(update);root.append(status,versions,impact,progress,details,actions,trouble);
 let closed=false,polling=false,starting=false,timer,current=null,lastVersion='',epoch=0;
 function draw(value){current=value;const working=starting||value.status==='working',pending=value.status==='awaiting_restart',server=value.local_server;
  if(server){lastVersion=server.version;versions.textContent=`Desktop app ${server.desktop_version} · Local server ${server.version}`;}
  status.textContent=pending?'Update ready · restart the local server to apply.':working?(value.stage||'Local server restarting · reconnecting…'):value.status==='error'?(value.message||'Local server needs attention.'):server?.update_available?'A local server update is available.':value.status==='ready'&&lastVersion?'Updated to '+lastVersion:server?'Local server is up to date.':value.message||'Local server is offline. Use Repair to start it again.';
  status.setAttribute('role',value.status==='error'?'alert':'status');progress.hidden=!working;progress.max=value.stage_count||5;if(Number.isFinite(value.completed_stages))progress.value=value.completed_stages;else progress.removeAttribute('value');log.textContent=value.detail||'';details.hidden=!value.detail;update.textContent=pending?'Restart local server':'Update local server';update.hidden=!server?.update_available&&!working&&!pending;update.disabled=working;repair.disabled=working||pending;impact.hidden=!working&&!pending&&!server?.update_available;
 }
 async function poll(){if(closed||polling)return;polling=true;const version=epoch;try{const value=await nativeInvoke('standalone_status',{});if(!closed&&version===epoch)draw(value);}catch(e){if(!closed){status.textContent=(current?.status==='working'?'Local server restarting · reconnecting…':'Could not check local server. Retrying…');}}finally{polling=false;if(!closed)timer=setTimeout(poll,current?.status==='working'?1000:5000);}}
 async function start(){if(starting||current?.status==='working'||closed)return;const count=workingBots();if(!confirm(`This interrupts active bot work and computer sessions.${count?' '+count+' bot'+(count===1?' is':'s are')+' working.':''} Continue?`))return;
  const command=current?.status==='awaiting_restart'?'restart_local_server':'prepare_local_server';epoch++;starting=true;draw({...current,status:'working',stage:command==='restart_local_server'?'Local server restarting · reconnecting…':'Preparing local server…'});try{await nativeInvoke(command,{});}catch(e){if(!closed)draw({status:'error',message:e.message||String(e)});}finally{starting=false;clearTimeout(timer);void poll();}}
 dialog?.addEventListener('close',()=>{closed=true;clearTimeout(timer);},{once:true});void poll();
}
